### ISSUE TITLE
Node crashes with exception "PeerInfo not found"

### ISSUE THREAD

**Issue by decryptoed** [blockcollider/bcnode#195]
Below is the exception.log that is written out

```
{
  "stack": [
    "Error: PeerInfo not found",
    "at PeerBook.get (/root/BLOCKCOLLIDER/bcnode/node_modules/peer-book/src/index.js:90:11)",
    "at MultiplexMuxer.muxedConn.once (/root/BLOCKCOLLIDER/bcnode/node_modules/libp2p-switch/src/dial.js:193:29)",
    "at Object.onceWrapper (events.js:272:13)",
    "at MultiplexMuxer.emit (events.js:180:13)",
    "at MultiplexMuxer.multiplex.on (/root/BLOCKCOLLIDER/bcnode/node_modules/libp2p-mplex/src/muxer.js:39:38)",
    "at Multiplex.emit (events.js:185:15)",
    "at Multiplex.destroy (/root/BLOCKCOLLIDER/bcnode/node_modules/libp2p-mplex/src/internals/index.js:476:10)",
    "at /root/BLOCKCOLLIDER/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45",
    "at call (/root/BLOCKCOLLIDER/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)",
    "at Array.forEach (<anonymous>)"
  ],
  "message": "PeerInfo not found"
}
```

**Comment by decryptoed** [comment]
Log file (Info-level logging) : https://transfer.sh/eiTbS/bcnode-2018041805.log

**Comment by korczis** [comment]
Attached log 

[Uploading bcnode-2018041805.log…]()
