### ISSUE TITLE
 UNCAUGHT EXCEPTION "message": "Cannot read property 'length' of null"

### ISSUE THREAD

**Issue by davidthamwf** [blockcollider/bcnode#199]
```
root@903c81e53f9d:/src# tail -f exception.log 
    "at nextTask (/src/node_modules/async/waterfall.js:16:14)",
    "at next (/src/node_modules/async/waterfall.js:23:9)",
    "at /src/node_modules/async/internal/onlyOnce.js:12:16",
    "at Object.reader.read [as cb] (/src/node_modules/pull-length-prefixed/src/decode.js:121:5)",
    "at drain (/src/node_modules/pull-reader/index.js:39:14)",
    "at more (/src/node_modules/pull-reader/index.js:51:13)",
    "at Object.reader.read (/src/node_modules/pull-reader/index.js:95:7)"
  ],
  "message": "Cannot read property 'length' of null"
```

![image](https://user-images.githubusercontent.com/26156139/39061182-0d13db2a-44f6-11e8-83c9-fbc54b747015.png)

**Comment by decryptoed** [comment]
Debug-level logs : https://transfer.sh/NAL0G/_logs-2018042021.log

**Comment by decryptoed** [comment]
This error occurs when the --node argument is passed.

**Comment by CryptoSmileee** [comment]
@decryptoed 
Do you still have this problem? I don't see this error on my miner.

**Comment by decryptoed** [comment]
No, I don't see it anymore.

**Comment by korczis** [comment]
Closing.
