### ISSUE TITLE
exception log, "stack" : [ "Error: already piped", ...

### ISSUE THREAD

**Issue by davidthamwf** [blockcollider/bcnode#208]
david@LinuxDocker:~/bcnode$ cat exception.log 
{
  "stack": [
    "Error: already piped",
    "at sink (/home/david/bcnode/node_modules/pull-pair/index.js:11:13)",
    "at consume (/home/david/bcnode/node_modules/pull-defer/sink.js:7:17)",
    "at consume (/home/david/bcnode/node_modules/pull-defer/sink.js:7:17)",
    "at Connection.consume (/home/david/bcnode/node_modules/pull-defer/sink.js:7:17)",
    "at pull (/home/david/bcnode/node_modules/pull-stream/pull.js:43:9)",
    "at Dialer.handle (/home/david/bcnode/node_modules/multistream-select/src/dialer/index.js:47:5)",
    "at protocolHandshake (/home/david/bcnode/node_modules/libp2p-switch/src/dial.js:216:10)",
    "at attemptMuxerUpgrade (/home/david/bcnode/node_modules/libp2p-switch/src/dial.js:65:11)",
    "at ms.select (/home/david/bcnode/node_modules/libp2p-switch/src/dial.js:177:15)",
    "at f (/home/david/bcnode/node_modules/once/once.js:25:25)"
  ],
  "message": "already piped"
}david@LinuxDocker:~/bcnode$ 

david@LinuxDocker:~/bcnode/lib/cli$ ./main.js --version
0.5.4#3870f93
![image](https://user-images.githubusercontent.com/26156139/39393691-eef451c8-4afa-11e8-88fc-c3c50545f5d3.png)
[exception.log](https://github.com/blockcollider/bcnode/files/1957424/exception.log)

might have something to do with the known ipfs issue (still open) reported before. https://github.com/ipfs/js-ipfs/issues/1156

**Comment by zengod1205** [comment]
Got similar error. 

p2p.node Error sending message to peer QmXk7xmWA4yShKUwXN7JZXatFX6ATRVYHzkL52tngTxhiW

> 2018-05-07T18:40:56.261Z INFO	bc.miner_worker Solution found: {
  "distance": 211444520780807,
  "nonce": "0.19157381279099228",
  "timestamp": 1525718473,
  "difficulty": 11801972029393,
  "iterations": 1,
  "timeDiff": 6
} 
2018-05-07T18:40:56.288Z INFO	engine.index Mined new block: {
  "hash": "061e5caa457c578f5f4ac50363b40420b1609ee7375530bd507c4fb4b3a96b71",
  "height": 615,
  "miner": "ZENGOD",
  "difficulty": 11801972029393,
  "timestamp": 1525718473,
  "merkleRoot": "452c4fdf84b95ad04c087cbcef7944c7e7ec16c5d80b63922bd7e45589a961ab",
  "chainRoot": "dc22b89978d49b796fc005631e07ab1fd8d8bc5d9f9ca29ff5866045f266b81c",
  "distance": 211444520780807,
  "nonce": "0.19157381279099228",
  "txCount": 0,
  "transactionsList": [],
  "childBlockchainCount": 5,
  "childBlockHeadersList": [
    {
      "blockchain": "btc",
      "hash": "0000000000000000004408dfe48c7451c6275d2f58a0dd66b96ec2d3c53518d6",
      "previousHash": "00000000000000000003bd15886b125d61b735fef747c5a31f9aa44afbbd4e9e",
      "timestamp": 1525718280000,
      "height": 521647,
      "merkleRoot": "ac22c93be76e0086b739069ce64fbed71a8aa5ba9903f3304d346a6940d48f7c",
      "childBlockConfirmationsInParentCount": 14
    },
    {
      "blockchain": "eth",
      "hash": "0xe72208893999a4a69a26e38b175ce46e35703e12b0103557ab45911e75263910",
      "previousHash": "0xa94ccb75bc1bc83543cc9ec699be7361758b569c0bc706bc6c8333635a1e48e2",
      "timestamp": 1525718433000,
      "height": 5573487,
      "merkleRoot": "0x23150b20007f58aaea1d94d1efcf7a0405c21d4b89d3d72f5d5e9158091ea70e",
      "childBlockConfirmationsInParentCount": 2
    },
    {
      "blockchain": "lsk",
      "hash": "3371133151079151548",
      "previousHash": "13209678546679460983",
      "timestamp": 1525718450000,
      "height": 5925309,
      "merkleRoot": "c45397537808c18936ae34465748579012ccdd8f724fbb0ae2a0cb19988401c4c20ea296e48fa424c4aa3373b39eb799d9b3c3bc7ad8b8c3d19130f03f88154e",
      "childBlockConfirmationsInParentCount": 1
    },
    {
      "blockchain": "neo",
      "hash": "0xe0867ba630a7dffa0ea77c1694cb96e5c7d321457d499d7020541e38cd39e87e",
      "previousHash": "0xdc4c5ba8ad8893106e07c6de584bbeb345fd412311e9872be9ad076b8ed01f8b",
      "timestamp": 1525718420000,
      "height": 2239561,
      "merkleRoot": "0x2a1a95c530fdfe44c07f81be61dfa536110473d70f4369553806cd7ec0af3b2b",
      "childBlockConfirmationsInParentCount": 4
    },
    {
      "blockchain": "wav",
      "hash": "4MRkFenzbT2kPJ19WFByxsvGRnCQniCeG4BQ4eeWDj9H3oMdRABfGyuFVad6THa65yv5mKjC6aEnZiEFz5n56y9i",
      "previousHash": "2h5MjUp7pjESGi6A7yP8wqWvCnfkBLej6n3SAeas7pfpPD2nL9eyv8Tag1r1MXdwscXdnTS3vcDxFddJgTthkmpV",
      "timestamp": 1525718261999,
      "height": 990863,
      "merkleRoot": "2e33d750fe4a520bc385d2fce387629fbfa2c26e66b6991db2085e10563e6e95cd0b64b95e4df9bf995f8fdfc9644b4dfca5f975827d36c16f933749513e62dc",
      "childBlockConfirmationsInParentCount": 28
    }
  ]
} 
2018-05-07T18:40:56.342Z INFO	engine.index Broadcasting mined block 
2018-05-07T18:40:59.772Z ERROR	p2p.node Error sending message to peer QmXk7xmWA4yShKUwXN7JZXatFX6ATRVYHzkL52tngTxhiW true 
2018-05-07T18:40:59.800Z ERROR	p2p.node Error sending message to peer QmXk7xmWA4yShKUwXN7JZXatFX6ATRVYHzkL52tngTxhiW true 
2018-05-07T18:41:00.024Z ERROR	p2p.node Error sending message to peer QmXk7xmWA4yShKUwXN7JZXatFX6ATRVYHzkL52tngTxhiW 
UNCAUGHT EXCEPTION, saving in exception.log Error: already piped
    at sink (/src/node_modules/pull-pair/index.js:11:13)
    at consume (/src/node_modules/pull-defer/sink.js:7:17)
    at consume (/src/node_modules/pull-defer/sink.js:7:17)
    at Connection.consume (/src/node_modules/pull-defer/sink.js:7:17)
    at pull (/src/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/src/node_modules/multistream-select/src/dialer/index.js:47:5)
    at protocolHandshake (/src/node_modules/libp2p-switch/src/dial.js:216:10)
    at attemptMuxerUpgrade (/src/node_modules/libp2p-switch/src/dial.js:65:11)
    at ms.select (/src/node_modules/libp2p-switch/src/dial.js:177:15)
    at f (/src/node_modules/once/once.js:25:25)
2018-05-07T18:41:00.425Z ERROR	p2p.node Error sending message to peer QmXk7xmWA4yShKUwXN7JZXatFX6ATRVYHzkL52tngTxhiW 
UNCAUGHT EXCEPTION, saving in exception.log Error: already piped
    at sink (/src/node_modules/pull-pair/index.js:11:13)
    at consume (/src/node_modules/pull-defer/sink.js:7:17)
    at consume (/src/node_modules/pull-defer/sink.js:7:17)
    at Connection.consume (/src/node_modules/pull-defer/sink.js:7:17)
    at pull (/src/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/src/node_modules/multistream-select/src/dialer/index.js:47:5)
    at protocolHandshake (/src/node_modules/libp2p-switch/src/dial.js:216:10)
    at attemptMuxerUpgrade (/src/node_modules/libp2p-switch/src/dial.js:65:11)
    at ms.select (/src/node_modules/libp2p-switch/src/dial.js:177:15)
    at f (/src/node_modules/once/once.js:25:25)
2018-05-07T18:41:00.613Z ERROR	p2p.node Error sending message to peer QmXk7xmWA4yShKUwXN7JZXatFX6ATRVYHzkL52tngTxhiW 
UNCAUGHT EXCEPTION, saving in exception.log Error: already piped
    at sink (/src/node_modules/pull-pair/index.js:11:13)
    at consume (/src/node_modules/pull-defer/sink.js:7:17)
    at consume (/src/node_modules/pull-defer/sink.js:7:17)
    at Connection.consume (/src/node_modules/pull-defer/sink.js:7:17)
    at pull (/src/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/src/node_modules/multistream-select/src/dialer/index.js:47:5)
    at protocolHandshake (/src/node_modules/libp2p-switch/src/dial.js:216:10)
    at attemptMuxerUpgrade (/src/node_modules/libp2p-switch/src/dial.js:65:11)
    at ms.select (/src/node_modules/libp2p-switch/src/dial.js:177:15)
    at f (/src/node_modules/once/once.js:25:25)
2018-05-07T18:41:00.679Z ERROR	p2p.node Error sending message to peer QmXk7xmWA4yShKUwXN7JZXatFX6ATRVYHzkL52tngTxhiW 
UNCAUGHT EXCEPTION, saving in exception.log Error: already piped
    at sink (/src/node_modules/pull-pair/index.js:11:13)
    at consume (/src/node_modules/pull-defer/sink.js:7:17)
    at consume (/src/node_modules/pull-defer/sink.js:7:17)
    at Connection.consume (/src/node_modules/pull-defer/sink.js:7:17)
    at pull (/src/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/src/node_modules/multistream-select/src/dialer/index.js:47:5)
    at protocolHandshake (/src/node_modules/libp2p-switch/src/dial.js:216:10)
    at attemptMuxerUpgrade (/src/node_modules/libp2p-switch/src/dial.js:65:11)
    at ms.select (/src/node_modules/libp2p-switch/src/dial.js:177:15)
    at f (/src/node_modules/once/once.js:25:25)
2018-05-07T18:41:00.732Z INFO	p2p.node Peers count 8 
2018-05-07T18:41:00.792Z ERROR	p2p.node Error dialing /status protocol QmXk7xmWA4yShKUwXN7JZXatFX6ATRVYHzkL52tngTxhiW 
UNCAUGHT EXCEPTION, saving in exception.log true
/src/lib/helper/error.js:42
  obj.stack = obj.stack.split('\n').map(line => line.trim()).filter(line => line !== '');
                        ^
2018-05-07T18:41:00.887604748Z 
TypeError: Cannot read property 'split' of undefined
    at errToObj (/src/lib/helper/error.js:42:25)
    at errToString (/src/lib/helper/error.js:54:15)
    at process.on.uncaughtError (/src/lib/cli/main.js:108:34)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:375:26)

**Comment by trick77** [comment]
@korczis bumping libp2p to 0.20.0 resolves the "already piped" errors since the transient dependency to libp2p-switch is updated as well. The "already piped" problem was a known bug in libp2p-switch 0.37.3. My bcnode is running more stable with 0.20.0.
