### ISSUE TITLE
Forced Quit

### ISSUE THREAD

**Issue by davidthamwf** [blockcollider/bcnode#225]
### Prerequisites

- [YES] Are you running the latest version?
- [BUILT FROM SOURCE] Are you running the docker image or did you built from source?
- [YES] Did you check the README.md for steps to run?
- [YES] Did you check logs? (either in console or in `_logs` directory)

For more information, see the `CONTRIBUTING` guide.

### Description

[Forced quit, multiple times, see attached error log]

### Steps to Reproduce

1. [Run miner latest build]
2. [Miner forced quit, restart]
3. [Forced quit again in about 20 mins]

**Expected behavior:** [No forced quit with uncaught exception]

**Actual behavior:** [Forced quit with uncaught exception]

### Versions
0.5.5/b320107

#### Application (required)

You can get this information:

- from executing `docker run blockcollider/bcnode --version` if running docker
- from executing `./bin/cli --version` if building from source
- in UI in the Navbar on top:

![UI version](./ui-version.png)

```
(replace with output from command above)
```

#### Environment (optional but helpful)

- OS Version (Ubuntu 16.04 LTS)
- Nodejs (v8.6.0)
- Rust (root@LinuxDocker:/home/david/bcnode# rustc -Vv
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
binary: rustc
commit-hash: ac3c2288f9f9d977acb46406ba60033d65165a7b
commit-date: 2018-04-18
host: x86_64-unknown-linux-gnu
release: 1.27.0-nightly
LLVM version: 6.0)

### Logs

2018-05-08T01:14:34.267Z INFO	engine.index Broadcasting mined block 
2018-05-08T01:14:34.269Z INFO	utils.time Stopping NTP time sync 
UNCAUGHT EXCEPTION, saving in exception.log Error: underlying socket has been closed
    at /home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:480:37
    at Array.forEach (<anonymous>)
    at Multiplex.destroy (/home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:478:10)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.onclose (/home/david/bcnode/node_modules/end-of-stream/index.js:48:54)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
    at Stream.s.destroy (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:146:7)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.onerror (/home/david/bcnode/node_modules/end-of-stream/index.js:43:12)
    at emitOne (events.js:120:20)
    at Stream.emit (events.js:210:7)
    at next (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:117:13)
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/async-map.js:28:19
    at callback (/home/david/bcnode/node_modules/pull-pushable/index.js:84:5)
    at drain (/home/david/bcnode/node_modules/pull-pushable/index.js:68:39)
    at Function.end (/home/david/bcnode/node_modules/pull-pushable/index.js:36:5)
    at decodeFromReader (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:25:27)
    at Object.reader.read [as cb] (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:63:14)
    at drain (/home/david/bcnode/node_modules/pull-reader/index.js:42:23)
    at /home/david/bcnode/node_modules/pull-reader/index.js:59:18
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at drain (/home/david/bcnode/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/david/bcnode/node_modules/stream-to-pull-stream/index.js:166:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
UNCAUGHT EXCEPTION, saving in exception.log Error: underlying socket has been closed
    at /home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:480:37
    at Array.forEach (<anonymous>)
    at Multiplex.destroy (/home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:478:10)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.onclose (/home/david/bcnode/node_modules/end-of-stream/index.js:48:54)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
    at Stream.s.destroy (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:146:7)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.onerror (/home/david/bcnode/node_modules/end-of-stream/index.js:43:12)
    at emitOne (events.js:120:20)
    at Stream.emit (events.js:210:7)
    at next (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:117:13)
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/async-map.js:28:19
    at callback (/home/david/bcnode/node_modules/pull-pushable/index.js:84:5)
    at drain (/home/david/bcnode/node_modules/pull-pushable/index.js:68:39)
    at Function.end (/home/david/bcnode/node_modules/pull-pushable/index.js:36:5)
    at decodeFromReader (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:25:27)
    at Object.reader.read [as cb] (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:63:14)
    at drain (/home/david/bcnode/node_modules/pull-reader/index.js:42:23)
    at /home/david/bcnode/node_modules/pull-reader/index.js:59:18
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at drain (/home/david/bcnode/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/david/bcnode/node_modules/stream-to-pull-stream/index.js:166:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
UNCAUGHT EXCEPTION, saving in exception.log Error: underlying socket has been closed
    at /home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:480:37
    at Array.forEach (<anonymous>)
    at Multiplex.destroy (/home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:478:10)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.onclose (/home/david/bcnode/node_modules/end-of-stream/index.js:47:54)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
    at Stream.s.destroy (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:146:7)
    at Stream.stream.on (/home/david/bcnode/node_modules/libp2p-mplex/src/index.js:15:33)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
    at next (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:118:41)
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/async-map.js:28:19
    at callback (/home/david/bcnode/node_modules/pull-pushable/index.js:84:5)
    at drain (/home/david/bcnode/node_modules/pull-pushable/index.js:68:39)
    at Function.end (/home/david/bcnode/node_modules/pull-pushable/index.js:36:5)
    at decodeFromReader (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:25:27)
    at Object.reader.read [as cb] (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:63:14)
    at drain (/home/david/bcnode/node_modules/pull-reader/index.js:42:23)
    at /home/david/bcnode/node_modules/pull-reader/index.js:59:18
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at q.get (/home/david/bcnode/node_modules/socket.io-pull-stream/src/index.js:78:16)
    at EventEmitter.ee.once (/home/david/bcnode/node_modules/data-queue/index.js:39:16)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at EventEmitter.emit (events.js:207:7)
    at Object.append (/home/david/bcnode/node_modules/data-queue/index.js:19:10)
    at Socket.SIOSource.sio.on.err (/home/david/bcnode/node_modules/socket.io-pull-stream/src/index.js:61:7)
    at Socket.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/home/david/bcnode/node_modules/socket.io-client/lib/socket.js:275:10)
    at Socket.onpacket (/home/david/bcnode/node_modules/socket.io-client/lib/socket.js:233:12)
    at Manager.<anonymous> (/home/david/bcnode/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/home/david/bcnode/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/home/david/bcnode/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at Decoder.add (/home/david/bcnode/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:251:12)
    at Manager.ondata (/home/david/bcnode/node_modules/socket.io-client/lib/manager.js:335:16)
    at Socket.<anonymous> (/home/david/bcnode/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:456:14)
    at WS.<anonymous> (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:273:10)
    at WS.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:145:8)
    at WS.Transport.onData (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:137:8)
    at WebSocket.ws.onmessage (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/websocket.js:147:10)
    at WebSocket.onMessage (/home/david/bcnode/node_modules/ws/lib/EventTarget.js:99:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/home/david/bcnode/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/david/bcnode/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/david/bcnode/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/david/bcnode/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/david/bcnode/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/david/bcnode/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
UNCAUGHT EXCEPTION, saving in exception.log Error: underlying socket has been closed
    at /home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:480:37
    at Array.forEach (<anonymous>)
    at Multiplex.destroy (/home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:478:10)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.onclose (/home/david/bcnode/node_modules/end-of-stream/index.js:47:54)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
    at Stream.s.destroy (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:146:7)
    at Stream.stream.on (/home/david/bcnode/node_modules/libp2p-mplex/src/index.js:15:33)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
    at next (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:118:41)
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/async-map.js:28:19
    at callback (/home/david/bcnode/node_modules/pull-pushable/index.js:84:5)
    at drain (/home/david/bcnode/node_modules/pull-pushable/index.js:68:39)
    at Function.end (/home/david/bcnode/node_modules/pull-pushable/index.js:36:5)
    at decodeFromReader (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:25:27)
    at Object.reader.read [as cb] (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:63:14)
    at drain (/home/david/bcnode/node_modules/pull-reader/index.js:42:23)
    at /home/david/bcnode/node_modules/pull-reader/index.js:59:18
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at q.get (/home/david/bcnode/node_modules/socket.io-pull-stream/src/index.js:78:16)
    at EventEmitter.ee.once (/home/david/bcnode/node_modules/data-queue/index.js:39:16)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at EventEmitter.emit (events.js:207:7)
    at Object.append (/home/david/bcnode/node_modules/data-queue/index.js:19:10)
    at Socket.SIOSource.sio.once (/home/david/bcnode/node_modules/socket.io-pull-stream/src/index.js:69:7)
    at Socket.on (/home/david/bcnode/node_modules/component-emitter/index.js:65:8)
    at Socket.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at Socket.emit (/home/david/bcnode/node_modules/socket.io-client/lib/socket.js:138:10)
    at Socket.onclose (/home/david/bcnode/node_modules/socket.io-client/lib/socket.js:214:8)
    at Manager.<anonymous> (/home/david/bcnode/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at Manager.onclose (/home/david/bcnode/node_modules/socket.io-client/lib/manager.js:502:8)
    at Socket.<anonymous> (/home/david/bcnode/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at Socket.onClose (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:720:10)
    at Socket.onError (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:686:8)
    at Socket.onPacket (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:452:14)
    at WS.<anonymous> (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:273:10)
    at WS.Emitter.emit (/home/david/bcnode/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:145:8)
    at WS.Transport.onData (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:137:8)
    at WebSocket.ws.onmessage (/home/david/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/websocket.js:147:10)
    at WebSocket.onMessage (/home/david/bcnode/node_modules/ws/lib/EventTarget.js:99:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (/home/david/bcnode/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/david/bcnode/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/david/bcnode/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/david/bcnode/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/david/bcnode/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/david/bcnode/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
Error: underlying socket has been closed
    at /home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:480:37
    at Array.forEach (<anonymous>)
    at Multiplex.destroy (/home/david/bcnode/node_modules/libp2p-mplex/src/internals/index.js:478:10)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.onclose (/home/david/bcnode/node_modules/end-of-stream/index.js:48:54)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
    at Stream.s.destroy (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:146:7)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/david/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/david/bcnode/node_modules/once/once.js:25:25)
    at Stream.onerror (/home/david/bcnode/node_modules/end-of-stream/index.js:43:12)
    at emitOne (events.js:120:20)
    at Stream.emit (events.js:210:7)
    at next (/home/david/bcnode/node_modules/pull-stream-to-stream/index.js:117:13)
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/async-map.js:28:19
    at callback (/home/david/bcnode/node_modules/pull-pushable/index.js:84:5)
    at drain (/home/david/bcnode/node_modules/pull-pushable/index.js:68:39)
    at Function.end (/home/david/bcnode/node_modules/pull-pushable/index.js:36:5)
    at decodeFromReader (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:25:27)
    at Object.reader.read [as cb] (/home/david/bcnode/node_modules/pull-length-prefixed/src/decode.js:63:14)
    at drain (/home/david/bcnode/node_modules/pull-reader/index.js:42:23)
    at /home/david/bcnode/node_modules/pull-reader/index.js:59:18
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/david/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at drain (/home/david/bcnode/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/david/bcnode/node_modules/stream-to-pull-stream/index.js:166:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
root@LinuxDocker:/home/david/bcnode# 2018-05-08T01:14:36.913Z INFO	rover.neo.controller parent exited 
2018-05-08T01:14:36.913Z INFO	rover.lsk.controller Parent exited 
2018-05-08T01:14:36.914Z INFO	rover.wav.controller Parent exited 
2018-05-08T01:14:36.915Z INFO	rover.btc.controller Parent exited 
2018-05-08T01:14:36.920Z INFO	rover.eth.controller Parent exited 
^C
root@LinuxDocker:/home/david/bcnode# cat exception.log 
{ stack: 
   [ 'Error: already piped',
     'at sink (/home/david/bcnode/node_modules/pull-pair/index.js:11:13)',
     'at consume (/home/david/bcnode/node_modules/pull-defer/sink.js:7:17)',
     'at consume (/home/david/bcnode/node_modules/pull-defer/sink.js:7:17)',
     'at Connection.consume (/home/david/bcnode/node_modules/pull-defer/sink.js:7:17)',
     'at pull (/home/david/bcnode/node_modules/pull-stream/pull.js:43:9)',
     'at Dialer.handle (/home/david/bcnode/node_modules/multistream-select/src/dialer/index.js:47:5)',
     'at protocolHandshake (/home/david/bcnode/node_modules/libp2p-switch/src/dial.js:216:10)',
     'at attemptMuxerUpgrade (/home/david/bcnode/node_modules/libp2p-switch/src/dial.js:65:11)',
     'at ms.select (/home/david/bcnode/node_modules/libp2p-switch/src/dial.js:177:15)',
     'at f (/home/david/bcnode/node_modules/once/once.js:25:25)' ],
  message: 'already piped' }

**Comment by CryptoSmileee** [comment]
I had the same error on my miner.
