### ISSUE TITLE
bc.miner_worker Mining failed with reason

### ISSUE THREAD

**Issue by CryptoSmileee** [blockcollider/bcnode#230]
### Prerequisites

- [x] Are you running the latest version?
- [BUILT FROM SOURCE] Are you running the docker image or did you built from source?
- [x] Did you check the README.md for steps to run?
- [x] Did you check logs? (either in console or in `_logs` directory)

For more information, see the `CONTRIBUTING` guide.

### Description
The log show that the miner has sometimes problem to mine:

### Steps to Reproduce

1. Run latest version of the miner

**Expected behavior:** Should check if the data used to store is valid

**Actual behavior:** 
The miner produce a warning with a stacktrace

### Versions
(0.5.5/9905e51)

#### Application (required)

You can get this information:
- Built from source
- Run the miner using forever:
`forever start ./bin/cli start --miner-key CryptoSmileee --node --ui --ws`

#### Environment (optional but helpful)

- OS Version (Ubuntu 17.10)
- Nodejs (v9.11.1)
- Rust (rustc 1.27.0-nightly (ad610bed8 2018-04-11))

### Logs
Full Log: http://telobot.com/UP_o.log

    2018-05-08T16:57:01.998Z WARN	bc.miner_worker Mining failed with reason: Number can only safely store up to 53 bits, stack Error: Number can only safely store up to 53 bits
    at assert (/home/bc/bcnode/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/home/bc/bcnode/node_modules/bn.js/lib/bn.js:506:7)
    at /home/bc/bcnode/lib/bc/miner_worker.js:54:81
    at mine (/home/bc/bcnode/lib/bc/miner.js:293:20)
    at process.on (/home/bc/bcnode/lib/bc/miner_worker.js:59:24)
    at process.emit (events.js:180:13)
    at emit (internal/child_process.js:783:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)

**Comment by akloboucnik** [comment]
Thanks for reporting @CryptoSmileee – I think this one is fixed by #220 which is in `master` branch just now so it should disappear after the next release but let's leave this open – I will take care of closing it after we test that it does not happen in the new version.

**Comment by akloboucnik** [comment]
Oh, now I see it also appears in master, no problem, will fix it soon.

**Comment by CryptoSmileee** [comment]
@akloboucnik 

I work with the latest version of master. And no problem, Tomas told me to report all this stuff here if I find something :)

**Comment by akloboucnik** [comment]
@CryptoSmileee sure, please do. You're doing great job! 👍
