### ISSUE TITLE
ERROR	p2p.node Error dialing /status protocol

### ISSUE THREAD

**Issue by CryptoSmileee** [blockcollider/bcnode#234]
### Prerequisites

- [x] Are you running the latest version?
- [x] Did you build from source?
- [x] Do you use the master branch?
- [x] Did you check the README.md for steps to run?
- [x] Did you check logs? (either in console or in `_logs` directory)

For more information, see the `CONTRIBUTING` guide.

### Description
There is a problem with the p2p connection

### Steps to Reproduce

1. Run latest version of the miner

**Expected behavior:** 
The error should be handled and should not crash the miner.

**Actual behavior:** 
If this error occure the miner crash.

### Versions
(0.5.5/9905e51)

#### Application (required)

You can get this information:
- Built from source
- Run the miner using forever:
`forever start ./bin/cli start --miner-key CryptoSmileee --node --ui --ws`

#### Environment (optional but helpful)

- OS Version (Ubuntu 17.10)
- Nodejs (v9.11.1)
- Rust (rustc 1.27.0-nightly (ad610bed8 2018-04-11))

### Logs
Full Log: http://telobot.com/UP_o.log

    2018-05-08T17:11:37.275Z ERROR	p2p.node Error dialing /status protocol QmcmGfpxSfhnkj9XuXVD8BVpYLJdvnaNN95QvhWpCQ5LEb 
    UNCAUGHT EXCEPTION, saving in exception.log Error: underlying socket has been closed
    at /home/bc/bcnode/node_modules/libp2p-mplex/src/internals/index.js:480:37
    at Array.forEach (<anonymous>)
    at Multiplex.destroy (/home/bc/bcnode/node_modules/libp2p-mplex/src/internals/index.js:478:10)
    at /home/bc/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/bc/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/bc/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/bc/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/bc/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/bc/bcnode/node_modules/once/once.js:25:25)
    at Stream.onclose (/home/bc/bcnode/node_modules/end-of-stream/index.js:47:54)
    at Stream.emit (events.js:185:15)
    at Stream.emit (domain.js:422:20)
    at Stream.s.destroy (/home/bc/bcnode/node_modules/pull-stream-to-stream/index.js:146:7)
    at Stream.stream.on (/home/bc/bcnode/node_modules/libp2p-mplex/src/index.js:15:33)
    at Stream.emit (events.js:185:15)
    at Stream.emit (domain.js:422:20)
    at next (/home/bc/bcnode/node_modules/pull-stream-to-stream/index.js:118:41)
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-stream/throughs/async-map.js:28:19
    at callback (/home/bc/bcnode/node_modules/pull-pushable/index.js:84:5)
    at drain (/home/bc/bcnode/node_modules/pull-pushable/index.js:68:39)
    at Function.end (/home/bc/bcnode/node_modules/pull-pushable/index.js:36:5)
    at decodeFromReader (/home/bc/bcnode/node_modules/pull-length-prefixed/src/decode.js:25:27)
    at Object.reader.read [as cb] (/home/bc/bcnode/node_modules/pull-length-prefixed/src/decode.js:63:14)
    at drain (/home/bc/bcnode/node_modules/pull-reader/index.js:42:23)
    at /home/bc/bcnode/node_modules/pull-reader/index.js:59:18
    at /home/bc/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at q.get (/home/bc/bcnode/node_modules/socket.io-pull-stream/src/index.js:78:16)
    at EventEmitter.ee.once (/home/bc/bcnode/node_modules/data-queue/index.js:39:16)
    at Object.onceWrapper (events.js:272:13)
    at EventEmitter.emit (events.js:180:13)
    at EventEmitter.emit (domain.js:422:20)
    at Object.append (/home/bc/bcnode/node_modules/data-queue/index.js:19:10)
    at Socket.SIOSource.sio.on.err (/home/bc/bcnode/node_modules/socket.io-pull-stream/src/index.js:61:7)
    at Socket.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/home/bc/bcnode/node_modules/socket.io-client/lib/socket.js:275:10)
    at Socket.onpacket (/home/bc/bcnode/node_modules/socket.io-client/lib/socket.js:233:12)
    at Manager.<anonymous> (/home/bc/bcnode/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/home/bc/bcnode/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/home/bc/bcnode/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at Decoder.add (/home/bc/bcnode/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:251:12)
    at Manager.ondata (/home/bc/bcnode/node_modules/socket.io-client/lib/manager.js:335:16)
    at Socket.<anonymous> (/home/bc/bcnode/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:456:14)
    at WS.<anonymous> (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:273:10)
    at WS.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:145:8)
    at WS.Transport.onData (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:137:8)
    at WebSocket.ws.onmessage (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/websocket.js:147:10)
    at WebSocket.onMessage (/home/bc/bcnode/node_modules/ws/lib/EventTarget.js:99:16)
    at WebSocket.emit (events.js:180:13)
    at WebSocket.emit (domain.js:422:20)
    at Receiver._receiver.onmessage (/home/bc/bcnode/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/bc/bcnode/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/bc/bcnode/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/bc/bcnode/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/bc/bcnode/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/bc/bcnode/node_modules/ws/lib/WebSocket.js:138:22)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
    2018-05-08T17:11:37.560Z ERROR	p2p.node Error sending message to peer Qmc1qq3kfW24GZ16FfUFqez4vvH5thjfvsWmXhutVQVvUy 
    2018-05-08T17:11:37.632Z ERROR	p2p.node Error sending message to peer QmehE833NXtPav9Qv2Tz5isvxry5rHaB258cBzZmBLwcnK 
    2018-05-08T17:11:37.689Z ERROR	p2p.node Error sending message to peer QmWQ8ppZo8irFYnhH4ZUcStxS6spk7rEqg9eVe8Hq91QZT 
    Error: underlying socket has been closed
    at /home/bc/bcnode/node_modules/libp2p-mplex/src/internals/index.js:480:37
    at Array.forEach (<anonymous>)
    at Multiplex.destroy (/home/bc/bcnode/node_modules/libp2p-mplex/src/internals/index.js:478:10)
    at /home/bc/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:45:45
    at call (/home/bc/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/bc/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:72:25
    at f (/home/bc/bcnode/node_modules/once/once.js:25:25)
    at Stream.<anonymous> (/home/bc/bcnode/node_modules/libp2p-mplex/node_modules/pump/index.js:31:21)
    at Stream.f (/home/bc/bcnode/node_modules/once/once.js:25:25)
    at Stream.onclose (/home/bc/bcnode/node_modules/end-of-stream/index.js:47:54)
    at Stream.emit (events.js:185:15)
    at Stream.emit (domain.js:422:20)
    at Stream.s.destroy (/home/bc/bcnode/node_modules/pull-stream-to-stream/index.js:146:7)
    at Stream.stream.on (/home/bc/bcnode/node_modules/libp2p-mplex/src/index.js:15:33)
    at Stream.emit (events.js:185:15)
    at Stream.emit (domain.js:422:20)
    at next (/home/bc/bcnode/node_modules/pull-stream-to-stream/index.js:118:41)
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-stream/throughs/async-map.js:28:19
    at callback (/home/bc/bcnode/node_modules/pull-pushable/index.js:84:5)
    at drain (/home/bc/bcnode/node_modules/pull-pushable/index.js:68:39)
    at Function.end (/home/bc/bcnode/node_modules/pull-pushable/index.js:36:5)
    at decodeFromReader (/home/bc/bcnode/node_modules/pull-length-prefixed/src/decode.js:25:27)
    at Object.reader.read [as cb] (/home/bc/bcnode/node_modules/pull-length-prefixed/src/decode.js:63:14)
    at drain (/home/bc/bcnode/node_modules/pull-reader/index.js:42:23)
    at /home/bc/bcnode/node_modules/pull-reader/index.js:59:18
    at /home/bc/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-reader/index.js:110:13
    at /home/bc/bcnode/node_modules/pull-stream/throughs/map.js:19:9
    at q.get (/home/bc/bcnode/node_modules/socket.io-pull-stream/src/index.js:78:16)
    at EventEmitter.ee.once (/home/bc/bcnode/node_modules/data-queue/index.js:39:16)
    at Object.onceWrapper (events.js:272:13)
    at EventEmitter.emit (events.js:180:13)
    at EventEmitter.emit (domain.js:422:20)
    at Object.append (/home/bc/bcnode/node_modules/data-queue/index.js:19:10)
    at Socket.SIOSource.sio.on.err (/home/bc/bcnode/node_modules/socket.io-pull-stream/src/index.js:61:7)
    at Socket.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/home/bc/bcnode/node_modules/socket.io-client/lib/socket.js:275:10)
    at Socket.onpacket (/home/bc/bcnode/node_modules/socket.io-client/lib/socket.js:233:12)
    at Manager.<anonymous> (/home/bc/bcnode/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/home/bc/bcnode/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/home/bc/bcnode/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at Decoder.add (/home/bc/bcnode/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:251:12)
    at Manager.ondata (/home/bc/bcnode/node_modules/socket.io-client/lib/manager.js:335:16)
    at Socket.<anonymous> (/home/bc/bcnode/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at Socket.onPacket (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:456:14)
    at WS.<anonymous> (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:273:10)
    at WS.Emitter.emit (/home/bc/bcnode/node_modules/component-emitter/index.js:133:20)
    at WS.Transport.onPacket (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:145:8)
    at WS.Transport.onData (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:137:8)
    at WebSocket.ws.onmessage (/home/bc/bcnode/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/websocket.js:147:10)
    at WebSocket.onMessage (/home/bc/bcnode/node_modules/ws/lib/EventTarget.js:99:16)
    at WebSocket.emit (events.js:180:13)
    at WebSocket.emit (domain.js:422:20)
    at Receiver._receiver.onmessage (/home/bc/bcnode/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/bc/bcnode/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/bc/bcnode/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/bc/bcnode/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/bc/bcnode/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/bc/bcnode/node_modules/ws/lib/WebSocket.js:138:22)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)

**Comment by CryptoSmileee** [comment]
I think this is related to #225
