### ISSUE TITLE
chttp2_server.cc Failed to initialize UV tcp handle

### ISSUE THREAD

**Issue by act1on3** [blockcollider/bcnode#249]
### Prerequisites

- version: Block Collider(0.5.5/e9d4379)
- docker image
- I use `docker run --rm --name bcnode -p 3000:3000 -p 9090:9090 blockcollider/bcnode:latest start --ws --rovers --ui --node --miner-key ABCDEF`
- logs
```
E0522 17:13:19.701764562       1 server_chttp2.cc:38]        {"created":"@1527009199.701714400","description":"No address added out of total 1 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":305,"referenced_errors":[{"created":"@1527009199.701705571","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.cc","file_line":436,"referenced_errors":[{"created":"@1527009199.701698344","description":"Failed to initialize UV tcp handle","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_uv.cc","file_line":277,"os_error":"address family not supported"}]}]}
2018-05-22T17:13:25.317Z ERROR	rover.wav.controller Error while collecting block { Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/src/node_modules/grpc/src/client.js:64:15)
    at /src/node_modules/grpc/src/client.js:583:15
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' } 
2018-05-22T17:13:25.717Z ERROR	rover.lsk.controller Error while collecting block { Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/src/node_modules/grpc/src/client.js:64:15)
    at /src/node_modules/grpc/src/client.js:583:15
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' } 
2018-05-22T17:13:26.016Z ERROR	rover.neo.controller Error while collecting block { Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (/src/node_modules/grpc/src/client.js:64:15)
    at /src/node_modules/grpc/src/client.js:583:15
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' }
```
and more errors like `Error while collecting block`

### Description

I use `hiveOS` for my mining rig.
When I try to launch bcnode, I get error. 
When  I  google it: [grpc issue](https://github.com/grpc/grpc/issues/12861)  
I  tried to use tweak `BC_GRPC_HOST`, but it is nothing

### Steps to Reproduce (for me)

1. run at hiveOS `docker run --rm --name bcnode -p 3000:3000 -p 9090:9090 blockcollider/bcnode:latest start --ws --rovers --ui --node --miner-key ABCDEF`
2. check logs
3. got errors

#### Application (required)

```
docker run blockcollider/bcnode --version
0.5.5#e9d4379
```

#### Environment (optional but helpful)

- [hiveOS](https://hiveos.farm/) 0.5-52
- Docker version 1.13.1, build 092cba3

**Comment by act1on3** [comment]
lol
I bypassed error with key `-e BC_GRPC_HOST=0.0.0.0`
But status is disconnect at web. All tabs are empty

**Comment by act1on3** [comment]
Goi it. Second problem is my fault - while experiment I forgot about `--ws` key.
How to resolve error from topic: you nedd to add key `-e BC_GRPC_HOST=0.0.0.0`
